import * as $ from '../gameObject/index.js'
import Vec2 from '../Vector.js'

export function Stage2(game) {
  game.levelData = {
    introDialogue: 'null',
    background: 'test',
    spawnpoint: new Vec2(635, 352),
    cameraHeight: 360,
    cameraBound: {
      x: 240,
      y: 270,
      width: 640,
      height: 360,
    },
    tileWidth: 160,
    tileHeight: 90,
  }

  game.tilePalette = ["Air","GlacialIce","BetterCementSnow","PaleLimestone","FadedBrickGrey","Rock","DarkRock","BetterSummitNoSnow","DarkRockMagma","ButternutBrick"]

  game.tileData = [
    '111111111                                                                                                                                                1      ',
    '11111111                                                                                                                                                 1      ',
    '1111111                                                                                                                                                  11     ',
    '111111                                                                                                                                                    1     ',
    '11111                                                                                                                                                     11    ',
    '1111                                                                                                                                                       11   ',
    '111                                                                                                                                                         1111',
    '11                                                                                                                                                             1',
    '1                                                                                                                                                               ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                  1111111111                                                                                    ',
    '                                                               11111111111111111                                                                                ',
    '                                                             1111111111111111111111                                                                             ',
    '                                                           111111        11111111111                                                                            ',
    '                                                          1111              111111111                                                                           ',
    '                                                         111                   1111111                                                                          ',
    '                                                        111                      111111                                                                         ',
    '                                                      1111                         11111                                                                        ',
    '                                                     1111                           11111                                                                       ',
    '                                                     111                              1111                                                                      ',
    '                                                   1111                                1111                                                                     ',
    '                                                   1111                                 1111                                                                    ',
    '                                                  111                                     1111                                                                  ',
    '                                                   1                                         11                                                                 ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '                                                                                                                                                                ',
    '1                                                                                                                                                             11',
    ' 11                                                                                                                                                          11 ',
    '   11                                                                                                                                                        1  ',
    '    1                                                                                                                                                       1   ',
    '     1                                                                                                                                         1            1   ',
    '      1                                                                                                                                        1                ',
    '       1                                                                                                                                       11               ',
    '       1                                                                                                                                        11              ',
  ]

  game.sound.playBGM('test')

  game.gameObjects.push(
  )
}
